### ISSUE TITLE
Exception: 数据库连接错误.... <class 'tortoise.exceptions.ConfigurationError'>: Unknown DB scheme:

### ISSUE THREAD

**Issue by rlzlrz** [Sakuracio/zhenxun_bot_docker#7]
部署命令是:
`docker run --name zhenxun_bot --link zhenxun_pg:pg -v /home/zhenxun_bot:/bot -e SU='<My QQ>' -e DB='postgres://postgres:<passwd>@pg:5432/zhenxun' hibikier/zhenxun_bot:latest`
然后是日志: 
> 04-18 19:16:45 [SUCCESS] nonebot | NoneBot is initializing...
04-18 19:16:45 [INFO] nonebot | Current Env: dev
04-18 19:16:45 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "chat_message"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "chat_history"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "ban"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "update_info"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "nickname"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "broadcast"
04-18 19:16:46 [SUCCESS] nonebot | Succeeded to import "invite_manager"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "admin_config"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "timing_task"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "switch_rule"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "rule"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "super_help"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "hooks"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "clear_data"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "exec_sql"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "reload_setting"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "manager_group"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "super_cmd"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "admin_help"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "plugin_shop"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "apscheduler"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "gold"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "use"
04-18 19:16:47 [SUCCESS] nonebot | Succeeded to import "buy"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "shop_handle"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "my_props"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "shop"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "help"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "scripts"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "group_handle"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "fudu"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "epic"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "fake_msg"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "ai"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "music"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "withdraw"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "white2black_image"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "translate"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "statistics"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "send_setu"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "update_setu"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "send_setu_"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "upload_image"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "send_image"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "move_image"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "delete_image"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "image_management"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "self_message"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "wbtop"
04-18 19:16:48 [SUCCESS] nonebot | Succeeded to import "message_handle"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "word_handle"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "word_bank"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "about"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "one_friend"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "coser"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "my_info"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "search_image"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "update_picture"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "mute"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "pid_search"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "web_ui"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "bt"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "aconfig"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "almanac"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "material_remind"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
04-18 19:16:49 [SUCCESS] nonebot | Succeeded to import "query_role"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "resin_remind"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "bind"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "mihoyobbs_sign"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "query_user"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "genshin"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "russian"
04-18 19:16:50 [SUCCESS] nonebot | Succeeded to import "sign_in"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "word_clouds"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "weather"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "search_anime"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "black_word"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "poke"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "check"
04-18 19:16:51 [SUCCESS] nonebot | Succeeded to import "what_anime"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "draw_card"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "dialogue"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "quotations"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "pix_update"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
04-18 19:16:52 [SUCCESS] nonebot | Succeeded to import "pix"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "luxun"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "yiqing"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "open_cases"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "comments_163"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "jitang"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "cover"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "poetry"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "alapi"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "roll"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "other_hook"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "ban_hook"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "auth_hook"
04-18 19:16:53 [SUCCESS] nonebot | Succeeded to import "task_hook"
04-18 19:16:53 [SUCCESS] nonebot | Running NoneBot...
04-18 19:16:53 [INFO] uvicorn | Started server process [10]
04-18 19:16:53 [INFO] uvicorn | Waiting for application startup.
04-18 19:16:53 [ERROR] uvicorn | Traceback (most recent call last):
  File "/bot/services/db_context.py", line 50, in init
    await Tortoise.init(db_url=i_bind, modules={"models": MODELS})
  File "/usr/local/lib/python3.9/site-packages/tortoise/__init__.py", line 537, in init
    config = generate_config(db_url, modules)
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/base/config_generator.py", line 189, in generate_config
    "connections": {_connection_label: expand_db_url(db_url, testing)},
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/base/config_generator.py", line 130, in expand_db_url
    raise ConfigurationError(f"Unknown DB scheme: {url.scheme}")
tortoise.exceptions.ConfigurationError: Unknown DB scheme: 

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/bot/services/db_context.py", line 54, in init
    raise Exception(f"数据库连接错误.... {type(e)}: {e}, i_bind:{i_bind}")
Exception: 数据库连接错误.... <class 'tortoise.exceptions.ConfigurationError'>: Unknown DB scheme:

> 04-18 19:16:53 [ERROR] uvicorn | Application startup failed. Exiting.
2023/04/18 19:16:54 exit status 3

大佬有什么头猪嘛？docker小白被弄懵了。pg是用docker部署的，在终端用psql能连上，新开一个pg容器也能连上，但是在这里不行欸...
大佬救一下QAQ

**Comment by Sakuracio** [comment]
请使用IP地址链接数据库， docker默认网桥不能使用pg:5432这种方式 或者自定义网桥 将数据库和Bot的docker放在同一个网桥

**Comment by rlzlrz** [comment]
已close，将postgres，go-cqhttp，zhenxun_bot三个镜像都挂在--network host下后解决。不过尝试新建docker network并放在自己建的network下，go-cqhttp好像会无法登录？
