### ISSUE TITLE
column "user_qq" does not exist

### ISSUE THREAD

**Issue by Phantom-Aria** [Sakuracio/zhenxun_bot_docker#9]
![image](https://github.com/Sakuracio/zhenxun_bot_docker/assets/6726462/cbf21acd-0b68-4c39-9385-149131abedc4)
按照[文档](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/psql_ubuntu.html)安装了Postgresql数据库，按照下面命令跑了docker：
`docker run --network=host -v /home/zhenxun_bot:/bot -e SU='1269035311' -e DB='postgres://postgres:zhenxun_bot@127.0.0.1:5432/zhenxun_bot' hibikier/zhenxun_bot:latest
`
前面加载都正常的，求助......TAT

**Comment by Phantom-Aria** [comment]
Postgresql用docker重新部署了一遍，没有这个报错了，好奇怪
重新跑了一遍zhenxun_bot的docker，卡在这一步没有下文了，也没有报错信息，就单纯的没有后续。。。。
![image](https://github.com/Sakuracio/zhenxun_bot_docker/assets/6726462/f9f287ef-aabd-45b7-8bf4-3e834442df6f)

**Comment by Sakuracio** [comment]
有问题吗？ 没问题呀 等待 Bot 连接

**Comment by Phantom-Aria** [comment]
回退了版本，现在没问题了~
